"""add knowledge document reference

Revision ID: 078a70f0956b
Revises: cc3951596874
Create Date: 2026-09-20 17:07:13.245027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "078a70f0956b"
down_revision: Union[str, Sequence[str], None] = "cc3951596874"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_documents",
        sa.Column(
            "document_reference",
            sa.String(length=100),
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        "uq_knowledge_documents_document_reference",
        "knowledge_documents",
        ["document_reference"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_knowledge_documents_document_reference",
        "knowledge_documents",
        type_="unique",
    )
    op.drop_column(
        "knowledge_documents",
        "document_reference",
    )
    # ### end Alembic commands ###